services:
  - type: web
    name: hoopster
    runtime: docker
    region: frankfurt
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_API_TOKEN
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: hoopster-data
      mountPath: /data
      sizeGB: 1 